AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Store eta-by-service info

  Sample SAM Template for Store eta-by-service info
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  storeEtaByServiceInfoBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  storeEtaByServiceInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: store-eta-by-service-info
      Handler: app.storeEtaByServiceInfoHandler
      Runtime: nodejs22.x 
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref storeEtaByServiceInfoBucket
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "s3:PutObject"
              Resource: !Sub arn:aws:s3:::${storeEtaByServiceInfoBucket}/*
      Events:
        storeEtaByServiceInfo:
          Type: Api
          Properties:
            Path: /store-eta-by-service-info
            Method: post



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StoreEtaByServiceInfoApi:
    Description: "API Gateway endpoint URL for store eta-by-service info"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
